language: node_js
node_js:
- "stable"
script:
- npm test
- npm run coverage
- npm install
after_success: 'npm run coveralls'
before_script:
   - npm install nyc coveralls codecov codeclimate-test-reporter -g
after_script:
   - codeclimate-test-reporter < ./coverage/lcov.info