language: node_js
node_js:
- "stable"
env:
 global:
   - export NODE_ENV=test
   - export SECRET_KEY=The Wisdom of God Rules the World
script:
- npm test
- npm run coverage
- npm install
after_success: 'npm run coveralls'
